# Generated by Django 4.2.7 on 2023-12-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_answerlike_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='avatar.jpg', max_length=150, null=True, upload_to='avatar/%Y/%m/%d'),
        ),
    ]
